### ISSUE TITLE
Can't remove items from character sheet

### ISSUE THREAD

**Issue by gravagehulk** [pwatson100/alienrpg#102]
Am I an idiot? I dragged some armor to a character and I can find no way to delete it from the character sheet. I have used a lot of different systems and VTT software and I've never had such a hard time just removing an item from inventory. What is the secret?

**Comment by gravagehulk** [comment]
It took me way too long to figure out that you have to right click on the "edit" button on the far right to delete.

**Comment by pwatson100** [comment]
Ha Ha.  That is why I wrote the MU/TH/ER Instructions journal entry.  And put a copy here: https://github.com/pwatson100/alienrpg/wiki/MU-TH-ER-Instructions
