### ISSUE TITLE
Initiatives not working as intended on new combatants

### ISSUE THREAD

**Issue by NeV3rKilL** [pwatson100/alienrpg#107]
If you add new combatants to a combat and roll initiative, It does not take in account the other initiatives and roll a new table, which ends up, repeating initatives.

A video better than 1000 words 
https://streamable.com/q9k7g0

**Comment by pwatson100** [comment]
It's a tricky one, but I understand the issue.  The challenge is what to do when the 10 initiative slots are full and another actor is added.  I will have to have a long hard think about how I might solve this one.

**Comment by pwatson100** [comment]
I think I have cracked it. Just testing and it will be in the next release.
