### ISSUE TITLE
Synthetic characters do not get max health filled

### ISSUE THREAD

**Issue by tosh823** [pwatson100/alienrpg#120]
Hi!

I've run into the issue with the synthetic characters. When I make a new character of that type and put some value in strength, I cannot make the HP bar appear on the token, because the max health property doesn't seem to be calculated, it stays at 0.
Human characters don't have this issue.

![Synth](https://user-images.githubusercontent.com/11402260/126362238-8d620eb1-9ccc-43dc-b001-904bc46efb21.PNG)

I am running:
Foundry version 0.8.8
Alien RPG version 2.0.2

Installed modules:
- Alien RPG - Motion Tracker;
- Alien RPG CRT UI (I tried disabling it, but the issue persists);
- AlienRPG Core Rulebook;
- AlienRPG Starter Set;
- Clocks;
- Dice So Nice!;
- Permission Viewer;
- Token Factions.

**Comment by pwatson100** [comment]
Hi,  Thank you.  This is a bug.  It's not calculating health.max for synthetics (the value on the right side of the / ).  By the looks of it it never has  :(
I will have it fixed in the next release.
