### ISSUE TITLE
Synthetic Stress Faking is very easily detected because of a bug

### ISSUE THREAD

**Issue by Theik** [pwatson100/alienrpg#124]
When a normal character rolls their stress, you can see by hovering over the Panic Condition, what their current stress level is:
![image](https://user-images.githubusercontent.com/6170572/127041818-745558ce-dbff-411f-95c2-554ec5f843dd.png)

However, if you do the same with a synethetic who is faking their stress tests, the attempt to read the stress level will not return 0, it'll instead return undefined because synethetic characters have no stress level:
![image](https://user-images.githubusercontent.com/6170572/127041936-a44c3a10-1a80-4f7d-8afb-4b3da701b3bc.png)

This makes it trivial to detect that a character is actually a synthetic, making the whole point of faking panic kind of moot. An easy fix would be to parse it to an integer first, making certain that that undefined becomes a 0.

**Comment by pwatson100** [comment]
Fair point.  I will look into it.

**Comment by pwatson100** [comment]
That was shockingly easy to fix :)    It will display 0 stress in future.
