### ISSUE TITLE
Stress rolls wont work on Character Sheet

### ISSUE THREAD

**Issue by corvoteimoso** [pwatson100/alienrpg#125]
Stress-Roll doesn't work. If i click on the stress on the character sheet, no Roll is commencing. If I click any other Skill or Attribute, the roll is happening. Any ideas, what could be wrong?

I already installed and reinstalled the module and the issue still goes on.
The version is 2.0.2

**Comment by pwatson100** [comment]
This is a known issue #123 and will be fixed in the next release. 

It's because the Panic Table has not been imported.  If you import it from the compendiums and put it in the mother tables folder it will work.

**Comment by corvoteimoso** [comment]
It worked as you said. Thank you very much and thanks for your amazing work.

All the best

**Comment by pwatson100** [comment]
Thank you.
