### ISSUE TITLE
Critical Injuries on Synthetics

### ISSUE THREAD

**Issue by Epsil0nNaught** [pwatson100/alienrpg#132]
Critical Injuries on Synthetics table does not exist in the rollable tables. When you roll on Synthetics sheet, error is produced

**Comment by pwatson100** [comment]
Core or Starter set? Are you using the latest version of the module(2.0.3)?  Can you check it is in the Compendium.  If it is you should be able to import it and move it to the Alien Mother Tables folder.

**Comment by Epsil0nNaught** [comment]
Looks like the core rule book. I loaded in the starter set and it was there. But it does not appear in the core rule book compendium. 
![Uploading 607B34BA-4BEC-4BAA-A384-55D0E46D5DDE.jpeg…]()

**Comment by pwatson100** [comment]
Ok you just need to import it from the starter set compendium. The issue with the core rules will be fixed in the next release.
