### ISSUE TITLE
Localization issues

### ISSUE THREAD

**Issue by Phenomen** [pwatson100/alienrpg#137]
1. `ALIENRPG.Seepage106` in English should reference page 104 since Permanent Trauma rules are on that page. 106 is "Other Hazards".
```js
chatMessage += `<h4><b>` + game.i18n.localize('ALIENRPG.PermanantTrauma') + `<i>(` + game.i18n.localize('ALIENRPG.Seepage106') + `) </i></h4></b>`;
```
2. Use `ALIENRPG.Weight` as a column header label in the Inventory instead of `ALIENRPG.AbbreviationKg`. Maybe you might want to add a string for Weight abbreviation like "Wght":
![image](https://user-images.githubusercontent.com/138311/138898326-abea398e-acec-4fa6-8dae-0624dcd883c3.png)

3.  Add `ALIENRPG.AbbreviationKg` localization here:
![image](https://user-images.githubusercontent.com/138311/138898609-34bb7507-7337-41ff-9daa-9e46d8e583ba.png)

4. Add localization support for attribute abbreviations:
![image](https://user-images.githubusercontent.com/138311/138898913-b5972e04-3bad-4e8c-ada4-4bc41a62afef.png)
![FoundryVTT_24MWIe7nvn](https://user-images.githubusercontent.com/138311/138898948-4d37c51c-9d27-4cba-995d-ffafc5bfc1de.png)

5. Add localization support to the following macros:
* Alien - Player Ad-hoc YZE Dice Roller
* Alien -  GM Dice Roller
* Alien - Roll on selected Creature table
* Alien - Roll on selected Mother table

6. The following issues are from **alienrpg-corerules.json**

**ALIENRPG.HeavyMachinery:** double `.` after "one"
**ALIENRPG.Manipulation:** missing `>` in </li> closing tag at the end

**Comment by pwatson100** [comment]
1.  I have changed that.  I think they added a page in the second printing of the rules. 
2. Having kg is explanatory to the vast majority of people.  Putting an abbreviation for Weight would only lead to more localization issues so I am not going to change it. 
3.  as above.
4. I agree and will look into it.  I am currently maintaining 7 languages so do not want to over complicate things. The majority of people are OK with the current abbreviations. 
5. I will look into it. 
6. alienrpg-corerules.json is not one of my files so I am not sure where that is coming from.

**Comment by Phenomen** [comment]
2. You don't need to create a new string, just use an existing  `"ALIENRPG.Weight"` string.

3. `"ALIENRPG.AbbreviationKg"` already exists in the translation json files and is used in weight column. You just need to use it in Encumbrance field instead of hardcoded "kg".
