### ISSUE TITLE
[Alien Core Rules] "Sub Table Critical Injuries on Xenomorphs" is in the wrong folder

### ISSUE THREAD

**Issue by Phenomen** [pwatson100/alienrpg#138]
Rollable table "Sub Table Critical Injuries on Xenomorphs" should be in the "Alien Mother Tables". Right now it shows up as an **attack rolltable** option in the creature character sheet, and it makes no sense since it's not an attack.

Also, "Critical Injuries on Xenomorphs" is already  in "Alien Mother Tables" so it's logical that they should be in the same folder.

**Comment by pwatson100** [comment]
There is no way I am aware of to restrict the list of tables returned from a specific folder so there is not way I can prevent other tables form showing in the dropdown.

**Comment by Phenomen** [comment]
@pwatson100 I think you misunderstood the issue.
Right now with current import settings table "Sub Table Critical Injuries on Xenomorphs" is being placed into "Alien Creature Tables" - all attacks are being pulled from this folder. Here you can see this table appear in dropdown:

![FoundryVTT_LnDAZiAQTo](https://user-images.githubusercontent.com/138311/139734343-6dd7beb5-5c0d-4af6-892f-fb2ba667026c.png)

But if you move it to **"Alien Mother Tables"** folder, it won't be in the dropdown and an issue will be fixed:

![FoundryVTT_hBQjRgao2w](https://user-images.githubusercontent.com/138311/139734445-17405822-0849-4ff5-8e31-6c753ec63fe9.png)
