### ISSUE TITLE
DoW - Journal Entries - Events Act 2 Issue

### ISSUE THREAD

**Issue by GittaNaba2021** [pwatson100/alienrpg#146]
Hello,

I noticed events from Act 2 (entry 10.3) have been replaced by events from Act 3 (entry 10.4). Events from both Act 1 and 3 are fine. I'm using DoW module 2.0.5.

Thanks for your help.

**Comment by pwatson100** [comment]
Hi, I did a fresh install and they look OK to me.    
Could you delete the those two journal entries and re run the import please.

**Comment by GittaNaba2021** [comment]
Hello, that did the trick for me, many thanks !

**Comment by pwatson100** [comment]
Super.
