### ISSUE TITLE
Outdated compendium definitions in alienrpg-corerules

### ISSUE THREAD

**Issue by r-valyar** [pwatson100/alienrpg#147]
The debug.log reports the following:
`{"level":"warn","message":"Package alienrpg-corerules contains 20 compendium definitions that still use the deprecated 'entity' field instead of 'type'.","timestamp":"2021-12-27 10:47:38"}`

Not sure what the imp act is currently or in future.

**Comment by mattsildo** [comment]
Your corerules' system index is working? Mine isn't working since the last updates. Maybe it's caused by that compendium definitions.

**Comment by pwatson100** [comment]
> The debug.log reports the following: `{"level":"warn","message":"Package alienrpg-corerules contains 20 compendium definitions that still use the deprecated 'entity' field instead of 'type'.","timestamp":"2021-12-27 10:47:38"}`
> 
> Not sure what the imp act is currently or in future.

Thank you.   I spotted this during my testing.  I am trying to find out exactly what it means.  I suspect it will need to be corrected before FVTT V10 comes out.  This is just a warning and does not appear to be having any impact on the system.  I am trying to find out exactly what it means.  I suspect it will need to be corrected before FVTT V10 comes out.

**Comment by pwatson100** [comment]
> Your corerules' system index is working? Mine isn't working since the last updates. Maybe it's caused by that compendium definitions.

Hi, I am assuming you are using FVTT V9, Alien V2.0.7 and Core Rules V2.04?  
Getting the links working was the main reason for the upgrades to the modules.  
I can only suspect the indexes were not updated correctly on your world.    Could you delete ALIEN RPG PLAYER RULES INDEX and ALIEN RPG GM RULES INDEX and re run the import (Configure Settings> Module Settings).
