### ISSUE TITLE
Character Sheet enhancements suggestions

### ISSUE THREAD

**Issue by GittaNaba2021** [pwatson100/alienrpg#148]
Hello,

Here are some suggestions to improve character sheet :

- Add a tooltip for stress button ("Click to roll for panic")
- Prevent "Health" and "Stress" values to go into negative
- Add a "Quantity" value for items (drugs by example)
- Make armor rolls also work directly from "Inventory" tab, not only "General" tab.

Thanks, and happy New year !

**Comment by pwatson100** [comment]
Hi,
  Thank you for the suggestions:

Add a tooltip for stress button ("Click to roll for panic")
            Very good Idea I will get that in the next release.

Prevent "Health" and "Stress" values to go into negative
           This is tricky but not impossible.  Field validation in Foundry is not straightforward.  But I will try. 

Add a "Quantity" value for items (drugs by example)
          I should be able to do this for items that have no weight otherwise it would mess up the encumbrance calculations.  But I will look into tit.   

Make armor rolls also work directly from "Inventory" tab, not only "General" tab.
         I should be able to do this and make it work like the power rolls. 


Happy New year.

**Comment by GittaNaba2021** [comment]
Looks great ! Quantity is useful for keeping track of tiny items, mostly drugs, so no need to modify the encumbrance calculations for it indeed.

**Comment by pwatson100** [comment]
I have manged three out of four.   
Preventing negative values in anything on the form seems to be unattainable as Foundry takes control of the field as soon as a new value is entered and does the update.  I have made it so the "minus" buttons don't allow the values to be less than zero.
