### ISSUE TITLE
DoW - Compiled list of issues of PC/NPC/Creatures Sheets

### ISSUE THREAD

**Issue by GittaNaba2021** [pwatson100/alienrpg#150]
Hello,

I'm compiling a list of issues from the DoW - I'm not finished yet, so I will continue to update it as I play the module.

I'm using FVTT 0.8.9, Alien RPG module 2.0.7, Alien RPG Core Rulebook 2.0.4, DoW module 2.0.5.

[Bugs]
Category : PC sheets

Dante's health is 7, not 5 by the rules - same error in book/pdf, so it's not specific to the module.

Chaplain owns a Cutting Torch as a weapon, but not as a tool.
Chaplain is missing ammo satchel item.
Chaplain is missing Surgical Kit weapon.

Hammer is missing four X-Stim syringes.

Silva is missing Combat Knife weapon.
Silva description age item : 4 of "43" is blue instead of green

Iona gear description typo : "M56 Smartgun" should be "M56A2 Smartgun"

Zmijewski is missing M240 Incinerator Unit weapon

Thanks for your help on this module !

**Comment by jamessthompson** [comment]
Another possible issue with the NPC sheets, setting the user permissions on an NPC sheet to limited does make the sheet read-only.  However, users can see things like personal agenda, description, etc.  The GM for our first alien game wants to make basic info on NPCs available but hide everything below the top bar.

**Comment by pwatson100** [comment]
> Another possible issue with the NPC sheets, setting the user permissions on an NPC sheet to limited does make the sheet read-only.  However, users can see things like personal agenda, description, etc.  The GM for our first alien game wants to make basic info on NPCs available but hide everything below the top bar.
> 
> 
> 
> If this should be a separate issue, let me know.
> 
> 

It's an issue with the system and not the modules. I have not implemented any visibility rules on the character sheets. Frankly I'm not sure where to start and with my current workload it's unlikely I will have a chance to look into it for a few months. Please feel free to open a specific issue.

**Comment by pwatson100** [comment]
Incorporated in to the V10 module release.
