### ISSUE TITLE
Add a "Critical Injuries" button on Creatures sheet when applicable

### ISSUE THREAD

**Issue by GittaNaba2021** [pwatson100/alienrpg#153]
Hello,

Adding a button similar to the one available within Player Character sheets would be a nice QoL improvement.

Regards,

**Comment by pwatson100** [comment]
I did look at this when I added it to the Character and Synth sheets.  But, from what I can see, only Xenomorphs have critical injuries.

**Comment by GittaNaba2021** [comment]
Hello, yes "Xenomorphs" would have been more appropriate than "Creatures".

**Comment by pwatson100** [comment]
Closed with V2.1.1 release
