### ISSUE TITLE
Supply Roll for power

### ISSUE THREAD

**Issue by lzago** [pwatson100/alienrpg#154]
The character sheets has the option to make a supply roll (byt he parachute botton aside) for every consumable but the power. According to the rules every time a player uses a motion tracker for instance needs to make this roll.

**Comment by pwatson100** [comment]
Power supply rolls are triggered on the Inventory sheet against the item as per the MO/TH/ER Instructions:
![image](https://user-images.githubusercontent.com/19948257/151183173-8526df4a-5ba9-45e5-848e-eec34847002a.png)
