### ISSUE TITLE
Creature Attack Rolls not GM-only messages as stated in MU / TH / ER instructions

### ISSUE THREAD

**Issue by KrisHammerberg** [pwatson100/alienrpg#165]
MU/TH/ER Instructions state that for creature attack rolls : "The result appears in the chat window as a GM only message, so the GM can narrate the action and add more flair and detail."

I'm testing the setup at the moment and if I logout as the GM and back in as a player, I can see those messages.  Is there some setting that needs to be toggled?

**Comment by pwatson100** [comment]
Hi, I forgot to update that when I made the change, it's controlled from the chat dropdown.  
I have updated it for the next release to read: 
_The result appears in the chat window as a "Public" message If you want the outcome to be private select the appropriate setting from the chat drop down._

**Comment by KrisHammerberg** [comment]
I figured this out on my own shortly after posting, but it is good to update the text! Thanks!
