### ISSUE TITLE
No chatlog styling for emote messages

### ISSUE THREAD

**Issue by cSelbrede** [pwatson100/alienrpg#175]
When typing an emote message in the chat log, such as "/me tries to scream", the chat log looks like this:

![162681022-231973b6-0cd2-45a8-badc-0bad581b1895](https://user-images.githubusercontent.com/203647/162875764-6e931e2a-96c9-4ae7-ac7f-39f0df0c60d2.png)

**Comment by pwatson100** [comment]
Thank you, I had not noticed that.  I will get it fixed in the next release.

**Comment by pwatson100** [comment]
Closed with V2.1.1 release
