### ISSUE TITLE
Item-Specific Power Supply Rolls

### ISSUE THREAD

**Issue by hornjbl** [pwatson100/alienrpg#176]
Firstly, thank you for an awesome system :-) 

Question on item-specific power rolls. 

In the inventory system, when I click on the power supply for a specific item, it does a power supply roll and automatically reduces the item's power supply.

Currently, it rolls a total amount of dice equal to my TOTAL power supply value. So, if I have two items, and both have power supply values, it will roll the amount of dice equal to the total of the two. 

If I have a flashlight with 5 power supply, and a cutting torch with 2 power supply, and I roll for power on the cutting torch, I would have expected it to only roll 2 dice, but it instead rolls 7 (flashlight power + cutting torch power). 

Is this a bug, or is it in accordance with the rules?
![Screenshot_1](https://user-images.githubusercontent.com/55430893/164881378-815a6992-fb25-4b01-a5fd-791e1d554a48.jpg)

**Comment by pwatson100** [comment]
Thank you, you are welcome.  
The Power is all explained in the mother instructions: 
![image](https://user-images.githubusercontent.com/19948257/164888136-12858d4f-4eb7-4fd0-bf1c-b1ee6e1b605e.png)
