### ISSUE TITLE
Duplicate Actors Created When Initiating Combat

### ISSUE THREAD

**Issue by twright-0x1** [pwatson100/alienrpg#184]
Configuration:  Alien RPG System version 2.1.2 with the Alien RPG Core Rule Book module (no other modules active)

If combat is initiated by selecting one or more stock actors (e.g., actors dragged onto the scene by selecting from the built-in Alien RPG Creatures) and one or more player-controlled actors, the stock actors are doubled inside the resulting Combat Tracker window.  This also appears to happen if actors are individually selected for combat.  Please see the attached screenshot.  

Also, attached is a screenshot of my browser's console immediately after selecting a group of actors for combat, right-clicking one, and clicking the Toggle Combat State token icon

<img width="959" alt="Screen Shot 2022-06-15 at 11 17 30 PM" src="https://user-images.githubusercontent.com/13889385/173985772-9a50316d-1faa-4c41-a417-2974296eb794.png">
<img width="1506" alt="Screen Shot 2022-06-15 at 11 21 14 PM" src="https://user-images.githubusercontent.com/13889385/173985786-8ceaac0a-30dc-4781-a7d7-74b07c115380.png">
.

**Comment by pwatson100** [comment]
Hi,  That is the correct behaviour for any creature with a speed > 1.  
As per the rules they get a number of goes per turn equal to their speed.

**Comment by twright-0x1** [comment]
Ah!  Thanks for clarifying that.  Makes sense.
