### ISSUE TITLE
Non-User-friendly Skill Names Displayed for Built-in Alien RPG Creatures

### ISSUE THREAD

**Issue by twright-0x1** [pwatson100/alienrpg#185]
Configuration: Alien RPG System version 2.1.2 with the Alien RPG Core Rule Book module (no other modules active)

When examining the actor sheets for any of the built-in Alien RPG Creatures, two of the skills listed appear to use internal representations of names, rather than user-friendly names:  "ALIENRPG.SKILLMOBILITY" and "ALIENRPG.SKILLOBSERVATION".  Please see the attached screenshot for an example.

<img width="803" alt="Screen Shot 2022-06-15 at 11 41 44 PM" src="https://user-images.githubusercontent.com/13889385/173987199-6a3dbf5d-7d26-4d04-87c7-ef7a7c39b74d.png">

**Comment by pwatson100** [comment]
Many thanks.  This has been fixed and will be in the next release #183 .  FYI, they ARMOR does not roll when pressed either.

**Comment by twright-0x1** [comment]
Thanks!  Appreciate the quick response.
