### ISSUE TITLE
[Suggestion] Token bars with a max value

### ISSUE THREAD

**Issue by Stefouch** [pwatson100/alienrpg#19]
Would it be possible to have token bars with a **current** value and a **max** value?
I am very interested in the following attributes:
- Health
- Stress
- Armor

**Comment by pwatson100** [comment]
I have the Health and Stress bars working and it was quite simple as I only needed to add "max":10 to the template.  The thing with Stress is when it's at the max the bar is coloured green which, in my opinion, gives the wrong signal.  I would like it to start green then gradually turn red as it get's to 10.  So I am looking into what I might be able to do.  Currently it looks like I would need to write a replacement for the code in Foundry!  Not really looking forward to that...

Armor is giving me a problem and I am wondering what it adds, so would appreciate your thoughts.  My thinking is that as the Armor number does not decrease all it would really do is show a filled (green) bar if armor has be activated.  And here lies the issue I am having....  I have to specify a "max" value for it which is fine, set it to 10 and you see the bar partially filled.  But once the sheet has been dragged onto the scene the bar does not change if the Armor is deactivated or activated.

**Comment by Stefouch** [comment]
> Armor is giving me a problem and I am wondering what it adds, so would appreciate your thoughts.

I was suggesting this one because armor can degrade and it would have been interesting to see it for some situation.
But I must admit an armor bar is secondary. Health and Stress will be the most useful.

> The thing with Stress is when it's at the max the bar is coloured green which, in my opinion, gives the wrong signal.

True, but don't be *stressed* about that. If your character reach 10 Stress ever, you would have been very lucky it didn't die before.

> Health

A small note: Health's max is equal to the Strength value, except for monsters (who don't have attributes) and for characters who have chosen the **Tough** talent.
