### ISSUE TITLE
No way to put items in backpack

### ISSUE THREAD

**Issue by jwylie01** [pwatson100/alienrpg#192]
There is now way to indicate items are in backpack and keep them from going towards encumbrance.

**Comment by pwatson100** [comment]
Right click on the edit box on the far right of the item: 
![image](https://user-images.githubusercontent.com/19948257/179457257-ff8a8767-cbdc-42fc-8000-fb92fb41aec7.png)

Items in the footlocker do not count toward encumbrance

**Comment by jwylie01** [comment]
That is what we are doing now and adding an ad-hoc note to indicate those items are in our packs. Would just be nice to have a section that is "backpack" to keep things separated and easier to track

**Comment by jwylie01** [comment]
ok
