### ISSUE TITLE
Nerves of Steel Inconsistent

### ISSUE THREAD

**Issue by NocFenix** [pwatson100/alienrpg#195]
Nerves of Steel Talent doesn't work consistently.

It seems to specifically quit applying when you switch scenes. Removing and re-adding the Talent for the character sheet when accessed via the associated Token on the new scene fixes it, but you have to do it for each scene.

**Comment by pwatson100** [comment]
Thank you.  I will look into it.  I have not noticed it.  The talent is part of the actor and is recalculated when the actor is updated so I am not sure why, for a linked actor, it would not be consistent.    Unlinked actors are a nightmare so it would not surprise me to see it happening there.

**Comment by pwatson100** [comment]
I am working o the V10 version and am struggling to recreate this.
I created a scene an put linked and unlinked actors on the scene with Nerves of Steel.  Both had the -2 to stress rolls.
I created a second scene and copied both actors (tokens) and pasted them on the new scene.  Again both worked as expected. 
Did a full restart of the world and it was still OK.  
Not quite sure what is going on.

**Comment by NocFenix** [comment]
I tried to replicate it recently too and couldn't, so I'm not 100% certain what caused it. Maybe version 10 will make it finally go away completely, or at least be more easily replicable.

**Comment by paranoicsan** [comment]
@pwatson100 thanks for your time working on this amazing project!

> I am working o the V10 version 

Do you have some vague timelines when the version with v10 support could be released? Current implementation can't be used to create characters and synths.

**Comment by pwatson100** [comment]
I don't have a date set for the v10 release. But it will not be until I have ported all the modules as well.  

I have not had any reports of people having issues creating actors in V9. 

Are you trying to use the released version in v10?

**Comment by paranoicsan** [comment]
> Are you trying to use the released version in v10?

@pwatson100 yep. I'm playing around with released version and the latest v10 build. If that will help I could create separate issue with a list of v10 issues I found. Didn't do that yet because thought you already know possible v10 related issues.

**Comment by pwatson100** [comment]
Thanks for offering but I know the v9 release will not work in v10. I have a v10 version I am testing.

**Comment by pwatson100** [comment]
I forgot to mention if you have a separate FVTT V10 install and a separate v10 data folder you could download the zip of my V10-T1 branch and have a play.

**Comment by paranoicsan** [comment]
Will do! Thanks for letting me know.

**Comment by paranoicsan** [comment]
@pwatson100 so, I've checked `V10-T1` branch - it does work without even warnings in console 🎉 
Will be waiting for modules to be updated. 

Will you post an update letting us know that premium modules have been updated?

**Comment by pwatson100** [comment]
Thank you.  My OCD kicked in and I wanted to get rid of all the warnings.    I uploaded a new V10-T1 this morning and corrected some issues with the CRT UI sheets.  

AS soon as the premium modules are done I will release the V10 system and put out a message.

**Comment by DarioLazzari** [comment]
Hello @pwatson100 we have noticed the same glitch in the ALIEN system, involving the Nerves of Steel Talent: it tend to not apply in the PC rolls until you erase and reassign it at the beginning of every session. But, doing this, it make a sort of cumulative -2 to Stress, going below zero. Very weird. Maybe I can post some screenshots of it, if it can be useful for you to better understand.

**Comment by pwatson100** [comment]
> @pwatson100 so, I've checked `V10-T1` branch - it does work without even warnings in console 🎉 Will be waiting for modules to be updated.
> 
> Will you post an update letting us know that premium modules have been updated?

Just checking in to see if you have found any issues with the V10 version.
The modules are ported to V10 and i have been testing them.  Just working with Free League to sort out a release date for V10.

**Comment by pwatson100** [comment]
> Hello @pwatson100 we have noticed the same glitch in the ALIEN system, involving the Nerves of Steel Talent: it tend to not apply in the PC rolls until you erase and reassign it at the beginning of every session. But, doing this, it make a sort of cumulative -2 to Stress, going below zero. Very weird. Maybe I can post some screenshots of it, if it can be useful for you to better understand.

Sorry for the delay in responding.

**Comment by DarioLazzari** [comment]
> > @pwatson100 so, I've checked `V10-T1` branch - it does work without even warnings in console 🎉 Will be waiting for modules to be updated.
> > Will you post an update letting us know that premium modules have been updated?
> 
> Just checking in to see if you have found any issues with the V10 version. The modules are ported to V10 and i have been testing them. Just working with Free League to sort out a release date for V10.

At the momenti, I don't know: I'm using V9 (I play on The Forge) because I'm worried about modules compatibility. Maybe I can check on the Foundry installed on my PC.

**Comment by pwatson100** [comment]
> > > @pwatson100 so, I've checked `V10-T1` branch - it does work without even warnings in console 🎉 Will be waiting for modules to be updated.
> 
> > > Will you post an update letting us know that premium modules have been updated?
> 
> > 
> 
> > Just checking in to see if you have found any issues with the V10 version. The modules are ported to V10 and i have been testing them. Just working with Free League to sort out a release date for V10.
> 
> 
> 
> At the momenti, I don't know: I'm using V9 (I play on The Forge) because I'm worried about modules compatibility. Maybe I can check on the Foundry installed on my PC.

No problem. Hopefully it all should be released in a couple of weeks so I was just wondering if you had come across anything.
