### ISSUE TITLE
Try to create Critical Injure table

### ISSUE THREAD

**Issue by yamilic008** [pwatson100/alienrpg#198]
Hello, I have tried to create the table, I have added it inside the folder "Alien Mother Table" and I have added some fields but when I click on the character sheet nothing happens, could you tell me how can I create the table?
![imagen_2022-09-18_042908976](https://user-images.githubusercontent.com/51417561/190895440-05b7bf43-4a49-4631-987a-f21999f63e17.png)

**Comment by pwatson100** [comment]
Hi, Sorry for the delay in responding.  
In the current version of the system (2.1.3) you can't create your own Critical injuries tables for Characters or Synthetics.  
I think I can allow this in the next release, which will be for Foundry V10.
