### ISSUE TITLE
No skin on players dice rolls from character sheet

### ISSUE THREAD

**Issue by krusty4president** [pwatson100/alienrpg#20]
Rolling the dice as Gamemasterthe dice looks as they should. Black dice and stress dice.
Rolling the dice from the character sheet as a player the dice from dice so nice skin is missing.
![image](https://user-images.githubusercontent.com/9943749/101137422-1898ab80-360f-11eb-964c-f7dc65e8c5a1.png)

The dice function work properly since correct dice roll outcome shows up in the chat. Its only the dice skin for players that fails to load

**Comment by Stefouch** [comment]
Is this done with the **Dice So Nice!** module ?

**Comment by krusty4president** [comment]
I think it is. Paul, the designer commented that on Foundry Discord channel some days ago.

**Comment by pwatson100** [comment]
This is an odd one I have been trying to get to the bottom of.  If I only have one dice system defined in DsN it works fine.  And if you (or the player) set the "Theme" to black, it works??
I have messaged JDW to see what I am doing wrong.

**Comment by Stefouch** [comment]
I had that skin bug too but then it disappeared. I don't know how (except I changed the dice color to black, but I may have modified other parameters).

**Comment by pwatson100** [comment]
Yea, that seems to cure it.   JDW is looking in to it.

**Comment by krusty4president** [comment]
A new observation while playing with dice so nice. 

If I go into DsN 3d settings as a player and set dice presets to "Alien RPG -full"  the black and yellow dice show up with full numbering.
If I change back to blank in the same dice preset the dice are still black and yellow with correct blank 2-5 faces.

See here
[https://youtu.be/ag-9AwLEQDI](url)

**Comment by pwatson100** [comment]
Really odd.  Hopefully JDW will be able to pin it down.

**Comment by pwatson100** [comment]
Hi,  I am going to close this issue as it's a problem with DsN.  The only thing I could do to solve it would be to enforce a single dice set which would upset those that want to have the numbers on the dice.

**Comment by krusty4president** [comment]
> Hi, I am going to close this issue as it's a problem with DsN. The only thing I could do to solve it would be to enforce a single dice set which would upset those that want to have the numbers on the dice.

Thats all fine, thanks for looking into it. Doing as I explained above makes the dice stay correct even after login and out:s. No need to change that after every login either. Cheers.
