### ISSUE TITLE
Add New 3D Dice to the System

### ISSUE THREAD

**Issue by brunocalado** [pwatson100/alienrpg#205]
Hi.

I made some dice for alien. I want to know if you can add them to the system.

Stress Static
https://user-images.githubusercontent.com/4999783/199053415-b935708a-ac62-4fe2-a703-3872fb639ed6.mp4

Animated
https://user-images.githubusercontent.com/4999783/199053639-b436bc27-725c-4aa0-9372-f8e6d183e1a3.mp4

They could be selected in DsN settings.
![image](https://user-images.githubusercontent.com/4999783/199053808-d8b8ba1d-eea7-400a-9656-cc1db3baf73f.png)

I can make the normal die work well, but the stress dice have some modifications I couldn't figure out. But, if you add to the system is easy to use.
```js
  // ---------------------------------------------------------
  // Alien Stress
  dice3d.addSystem({id:"alien_stress-extradice", name:"Alien Stress - ED"}, false);
  
  dice3d.addDicePreset({
    type:"ds",
    system:"alien_stress-extradice", 
    modelFile: 'modules/' + moduleName + '/models/alien/alien_stress.glb'    
  }); 
```

You can get the dice or test them with the module at: https://github.com/brunocalado/extra-dice

**Comment by pwatson100** [comment]
Thank you for offering.
They are very nice dice, and you have done a great job, but I do not want to take on any extra responsibility for maintaining extra dice in the system.  Additionally, I would need approval from Free League as they do not fit in with the overall aesthetic of the Alien system.     

Could I suggest you release them as a module like https://foundryvtt.com/packages/lordudice

**Comment by brunocalado** [comment]
> Thank you for offering. They are very nice dice, and you have done a great job, but I do not want to take on any extra responsibility for maintaining extra dice in the system. Additionally, I would need approval from Free League as they do not fit in with the overall aesthetic of the Alien system.
> 
> Could I suggest you release them as a module like https://foundryvtt.com/packages/lordudice

I can't bypass the stress dice. You made something with it. I already create a module for it.

If you run /r 1db or /r 1ds you can see the new dice. BUT, if you use the system call you will not see it.

**Comment by brunocalado** [comment]
If you don't to add the dice, I can push them to some place or release the module. But, the stress dice is something I couldn't figure out.

You can install the module to make some tests.

https://github.com/brunocalado/extra-dice

**Comment by pwatson100** [comment]
The Stress button does a 1d6 roll against the panic table.
 let modRoll = '1d6' + '+' + parseInt(aStress);

So, the only way to get it to roll stress dice would be for me to change that code to roll a stress dice 
        let modRoll = '1ds' + '+' + parseInt(aStress);
That would work for your custom dice but as the standard stress dice in the system do not have numbers would break for the other users.
