### ISSUE TITLE
Migrated Tough Talent Creating problems on sheet

### ISSUE THREAD

**Issue by jacksands** [pwatson100/alienrpg#207]
Hi! first tks for your work! I'm having a blast playing Alien!

I had encountered a strange behavior related to the Tough Talent. My game is migrated from V9, and I start noticing that when a player have his sheet opened I cannot properly interact with the same sheet, sometimes the foundry even crashes, but without any console errors... Test with no modules but the officials and rebuilding the sheet from the start I was able to define the error to the tough talent.

I tested it on a brand new world and it do not happens, even importing the actor from the world with the error  to the new. So I suppose it is only because it is an migrated world.

Strangely deleting the talent and reimporting it from the module do not solves it.

I don't mind rebuilding my world from the start, I can use compendiums and such, but can you give a look if you can?

 I have made a video showing a GM screen and a PC screen trying to use the sheet, and if you want I can send the world zipped as well!

Once again tks for your help!

Erich

https://user-images.githubusercontent.com/7229143/200126537-a53fb9d6-8e06-4b52-9042-e5dedfddedeb.mp4

**Comment by pwatson100** [comment]
That is very odd.  If you create a new actor and do the same thing with the Tough talent, does it still go wrong?

**Comment by jacksands** [comment]
yes, this is a brand new character created on the world where the error occurred...

also removing the talent solves the issue on old characters...

**Comment by pwatson100** [comment]
Also, could you try it with the CRT UI disabled. (you are using the built in CRT UI?).

**Comment by jacksands** [comment]
also tested with the migrated talent and deleting it from the world and re importing only this talent causes the same error...
have no idea why

**Comment by jacksands** [comment]
already tried disable the crt, and it is the built-in one

**Comment by jacksands** [comment]
the only thing I haven't try is to open the same world on other foundry install in a different computer only to see if the issue persist

**Comment by pwatson100** [comment]
I can see from your video that when you remove/add the talent that the max health is being changed on the GM and Player screens.  Are there any errors showing in the player console?

**Comment by jacksands** [comment]
no, no console errors at all...
only the sheet becames unresponsive...

**Comment by pwatson100** [comment]
Could you zip up your world and send me it on Discord? Let's see if it happens on my machines.

**Comment by jacksands** [comment]
yes, I will do it as soon as possible...
tks for the effort!

**Comment by pwatson100** [comment]
No problem.  Forgot to ask, does it happen with all other modules disabled? 

If you can DM it to me I will have a look.

**Comment by pwatson100** [comment]
OK.  Bad news.  It's hapening to me as well.  So don't worry about the world.

**Comment by pwatson100** [comment]
Found the issue, just need to work out how to fix it!

**Comment by jacksands** [comment]
ok, that's bad, I hoped it was local so no one else would have this issue...
if I can help just say it

**Comment by jacksands** [comment]
> 

wow!  that fast!!

**Comment by pwatson100** [comment]
For some reason, I need to determine, if you add TOUGH or NERVES OF STEEL the sheet goes into a loop.

**Comment by pwatson100** [comment]
Thank you for identifying that issue.  TBH, I had not seen it before.  I suspect it was because I did not have a player window open when I was testing.

**Comment by jacksands** [comment]
i thank you for the amazing work!
that's no way you could test everything, with hundreds of world now active something will show, the fact that has been so little issues so far is a testimony to a work well done by you!

tks
