### ISSUE TITLE
The editor buttons are black on black

### ISSUE THREAD

**Issue by krusty4president** [pwatson100/alienrpg#21]
The buttons of the description editor in the character sheet are invisible since the color is black on black. They only show on hoovering
![image](https://user-images.githubusercontent.com/9943749/101138845-00299080-3611-11eb-9a2e-4f4bc2adb497.png)

**Comment by pwatson100** [comment]
I have checked the Character, Synthetic and Creature sheets and can't reproduce the issue.  What version of Alien are you currently on?   There was an issue with the editor not displaying at all but I corrected it in V1.2.15.

**Comment by krusty4president** [comment]
![2020-12-04_15-24-37](https://user-images.githubusercontent.com/9943749/101174983-e144f180-3644-11eb-8a3e-8613078d785f.gif)

Thats strange. This is how it looks like here.

**Comment by pwatson100** [comment]
But what version are you using?  
Can you disable all add ins and try again.

**Comment by krusty4president** [comment]
Im using 1.2.16 of the game system. I will try run it with the ”find the culprit” Foundry module when im back at my computer.

**Comment by krusty4president** [comment]
I have disabled a bunch of not needed modules and not it works. If I find the time I can go through them all and check. But now its working The entire edito went white instead, but thats better. At least its easier to see

**Comment by pwatson100** [comment]
Well we are getting there.  The edit window should be white with black text.
