### ISSUE TITLE
Nerves of steel applying to Itens Rolls.

### ISSUE THREAD

**Issue by jacksands** [pwatson100/alienrpg#216]
Hi! once again tks for your work!

I'm having an issue lately, at foundry v10 - 290 and Alien 3.0.4.

If rolling directly from the inventory the Nerves of Steel Talent is reducing from the dice rolled, but only when fron the itens.

Sending you videos, if you can take a look I would appreciate!

https://user-images.githubusercontent.com/7229143/204111776-f829a420-1e3a-43fd-a189-6d4394be9806.mp4

https://user-images.githubusercontent.com/7229143/204111793-1cd96fd5-f111-4021-9734-4f6fc17b3a30.mp4

**Comment by pwatson100** [comment]
Ah.  Good spot.  That's wrong.  The -2 should only be coming off of Panic/Stress rolls.  
Found the offending line of code and it will be fixed in the next release.
Thank you for letting me know.
