### ISSUE TITLE
Auto scale token

### ISSUE THREAD

**Issue by jwylie01** [pwatson100/alienrpg#217]
Add an option to auto-scale tokens to grid size. Will help when moving tokens across maps so GM doesn't have to stop and resize everything to match grid size

**Comment by pwatson100** [comment]
Hi Jennifer,  
That is a really good suggestion.  I would be great if Foundry did that out of the box.
Not sure if I can actually do it but I will look into it.  
The maps scales for Alien (and Symbaroum) are a bit of a balancing act between allowing the grids to be accessible and keeping the overall scene sizes reasonable.  So, I fully appreciate the issue.  
Paul.

**Comment by pwatson100** [comment]
I have looked into this and am afraid I am not going to be able to do it.  Overall, it's just far too complex to code and would likely cause more issues with tokens.  
Sorry.

**Comment by jwylie01** [comment]
Thanks for looking into it. Was just a random thought I had during a session one day because the GM kept having to stop and resize tokens on new maps.
