### ISSUE TITLE
Missing manifest file?

### ISSUE THREAD

**Issue by krusty4president** [pwatson100/alienrpg#22]
![image](https://user-images.githubusercontent.com/9943749/101209458-0bfa6e80-3674-11eb-98e7-c1adb17312e2.png)

Hi. Getting this while trying to update to latest 1.2 18

**Comment by krusty4president** [comment]
You need to change the link. It seems the new has been pasted after the old one instead of paste/exchanging the old one.

Manually entering the last part of the URL in the error message works.

**Comment by pwatson100** [comment]
I made a copy/paste error when I updated the Foundry site.  I have corrected it now.
