### ISSUE TITLE
Spelling errors in Alien RPG Player Guide

### ISSUE THREAD

**Issue by mogrogh** [pwatson100/alienrpg#222]
All below is from the journal Alien RPG Player Guide

Comtech skill description:
STUNTS: For each extra [dice] olled beyond

Olled? Rolled!

**Comment by mogrogh** [comment]
Also Scientist Talent "Analysis" the dice symbol is missing:
For every [missing dice symbol] you roll,

**Comment by mogrogh** [comment]
Combat & Panic
And alien species aren’t the only danger.People on the Frontier are jerks.

No space after the dot.

**Comment by mogrogh** [comment]
Time & Space
Borders & Line of Sight
the two zones.Open borders

No space after the dot.

**Comment by mogrogh** [comment]
Under Other Hazard and Disease and under OTHER DISEASES

The bullet-list for disease is repeated. Seems like a mistake.

**Comment by mogrogh** [comment]
I've seen a few referenses to Chariot of the Gods, like under Xenomorph in Other Hazards:

In combat, Xenomorphs follow special rules. More information for the GM can be found in the Chariot of the Gods scenario. 

Not sure if this is suipposed to be there. I'm reading the core book, not the starter set. I only have the modules, not the books.

**Comment by mogrogh** [comment]
Under Weapons & Armor

 with the Blast Power indicated.Range is the maximum

No space after dot.

**Comment by mogrogh** [comment]
Under Living in space and the Arceon description just ends mid sentence.

W-Y ships stopped running supplies to Arceon after Tomas died decades ago, and the monks

**Comment by mogrogh** [comment]
Under Spacecraft Basics

commander and pilot are stationed here.SENSORS: Spaceships 

Sensors should be it's own paragraph.
![bild](https://user-images.githubusercontent.com/69079040/212487823-44ac83a2-1eb5-405e-89ac-7b51db894430.png)

**Comment by mogrogh** [comment]
Under Spacecraft Basics under Armamnet:

target individuals.The weapons

No space after dot.

**Comment by mogrogh** [comment]
Under Spacecraft Basics ander Upgrades:

Read more about ths in the LANETFALL box above. 

P is missing: PLANETFALL

**Comment by mogrogh** [comment]
Under Space Combat and Approach Velocity:

is zero.If more than

No space after dot.

**Comment by mogrogh** [comment]
Under Space Combat Panic Roll the result is presented differently. Maube settle with all caps?

![bild](https://user-images.githubusercontent.com/69079040/212494494-51e0a1d5-126b-4d8b-bd26-5ed1ce6bbc2d.png)

**Comment by mogrogh** [comment]
Under Major Component Damage

Bridge exposedto vacuum

Space is missing "exposed to".

**Comment by mogrogh** [comment]
Under Minor Component Damage:

35 |   | Displacement drive malfunction | **FTL rating halved.** | HEAVY MACHINERY + COMTECH

Probably not a spelling error but an error in the rules. I'm pretty sure the ship will be slower when damaged, not faster. Probably should be FTL rating doubled.

**Comment by mogrogh** [comment]
OK, I'm done reading this journal.

**Comment by pwatson100** [comment]
Many thanks for this.  I have made the changes and they will be in the next release.  Been a bit busy so decided to do it along with the FVTT V11 release.  

> Under Minor Component Damage:
> 
> 35 |   | Displacement drive malfunction | **FTL rating halved.** | HEAVY MACHINERY + COMTECH
> 
> Probably not a spelling error but an error in the rules. I'm pretty sure the ship will be slower when damaged, not faster. Probably should be FTL rating doubled.

I agree, I have checked the 6th edition as well as the FL forum for the errata and it's not been flagged so I will have to leave it I am afraid..
