### ISSUE TITLE
Spelling errors in Alien RPG GM Guide

### ISSUE THREAD

**Issue by mogrogh** [pwatson100/alienrpg#223]
In Game Principles

**You are the Xeno­morph.Being a GM takes some work**

No space after dot.

**Comment by mogrogh** [comment]
Under Cinematic Play

**PCs will be lucky to survive.Cinematic play takes**

No space after dot.

**Comment by mogrogh** [comment]
Under Campaign Play

**afford a cheap room on Anchorpoint station.Goals might change**

No space after dot.

**Comment by mogrogh** [comment]
Under Big Business, Big Government

**Weyland-Yutani doesn&'t own everything**

A &-sign that isn't supposed to be there.

**Comment by mogrogh** [comment]
Under Weyland-Yutani

The right type of header?
![bild](https://user-images.githubusercontent.com/69079040/212607634-136c1399-42ba-421c-9895-49e5a462a2f5.png)

**Comment by mogrogh** [comment]
Under Seegson.

The right header? All other has the green as in the image in the post above, except for the first. Seegson has the blue on all.
![bild](https://user-images.githubusercontent.com/69079040/212609474-a1b794c9-5cb7-4b5b-bef3-26a5044d227f.png)

**Comment by mogrogh** [comment]
Under The Outer Veil

**nitor the planet.Now, a cre**

No space after dot.

**Comment by mogrogh** [comment]
Under the Outer Veil and FURY 161: RUMOR CONTROL

**Ripley and Morse > managed to**

A > in the middle of the sentence.

**Comment by mogrogh** [comment]
Under The Frontier and LV-223: RUMOR CONTROL

**Excavator Vessel known as > the Onager.**

A > in the middle of the sentence.

**Comment by mogrogh** [comment]
Under Other extrasolar species


    **Type:Mammalian Omnivore
    Habitat:Tartarus and several mining colonies.
    Size:6 meters or more
    Traits:Erupts from ground, stampedes when threatened, charges when cornered. Doesn't know when to retreat.**

No space after colon.

**Comment by mogrogh** [comment]
Under The Xenomorphs, under STAGE I: OVOMORPH (EGG)

![bild](https://user-images.githubusercontent.com/69079040/213112827-ec15c05e-f1e3-4707-a670-fc3729191fce.png)

New paragraph is directly after previous sentence.

**Comment by mogrogh** [comment]
Under The Xenomorphs and STAGE II: FACEHUGGER

FACEHUGGER AND Praeto-Facehugger: 

All other are all caps except this.

**Comment by mogrogh** [comment]
Under THE CAMPAIGN FRAMEWORK and SPACE TRUCKERS

**stint is worth a full share.As the**

No space after dot.

**Comment by mogrogh** [comment]
Novgorod Station under Overview.

**doors to that deck.The ten decks of**

No space after dot.

**Comment by mogrogh** [comment]
OK, done reading this journal.

**Comment by pwatson100** [comment]
Many thanks for this.  I have made the changes and they will be in the next release.  Been a bit busy so decided to do it along with the FVTT V11 release.
