### ISSUE TITLE
Spelling error in Hope's Last Day - Scenario

### ISSUE THREAD

**Issue by mogrogh** [pwatson100/alienrpg#224]
Under 01. INTRODUCTION

**unlikely of colonies.Hope's Last Day**

No space after dot.

**Comment by mogrogh** [comment]
Under 02. THE SITUATION

**hive proper.When a Weyland**

No space after dot.

**Comment by mogrogh** [comment]
Under 06. EPILOGUE

**lot of fun!Story Points**

No space after exclamation mark.

**Comment by mogrogh** [comment]
Done reading this journal.

**Comment by pwatson100** [comment]
Many thanks for this.  I have made the changes and they will be in the next release.  Been a bit busy so decided to do it along with the FVTT V11 release.
