### ISSUE TITLE
spacecraaft-sheet

### ISSUE THREAD

**Issue by SilverwolfNL** [pwatson100/alienrpg#225]
Mayeb more a question than bug. Seeing spacecraft-sheet   in code. But not implemented in final UI. any plans to implement it?  or am i missing something?

**Comment by pwatson100** [comment]
It’s not implemented yet. Regards,  Paul.Tel: 01708 700482Mob: 07415 119787On 28 Jan 2023, at 20:31, SilverwolfNL ***@***.***> wrote:﻿
Mayeb more a question than bug. Seeing spacecraft-sheet   in code. But not implemented in final UI. any plans to implement it?  or am i missing something?
