### ISSUE TITLE
Add a new sheet: Starships

### ISSUE THREAD

**Issue by FederSchakal** [pwatson100/alienrpg#229]
Hey,

It would be useful to add a starship sheet for starship battle.
For every module, enhancement, weapon etc. 

Thanks for ur attention :)

**Comment by pwatson100** [comment]
Hi, 
  thank you for the feedback.  I have been working on the starship sheet for a while.  Not sure when it's going to be completed as I have other work I need to be completing which is taking up a lot of my time.

**Comment by pwatson100** [comment]
Fixed in the 3.1.0 update
