### ISSUE TITLE
Token Prototype Issues

### ISSUE THREAD

**Issue by patrickburk1988** [pwatson100/alienrpg#231]
I've noticed two issues with actor token prototypes:

1. Regardless of whether the `Default Prototype Token Settings` setting is enabled or disabled, all newly created actors have their `Display Name` and `Display Bars` values set to `Hovered by Owner` and their `Token Disposition` value set to `Friendly`. This is true even if the core `Default Token Configuration` values are set to something else. I can reproduce this in a new game with no other modules enabled.
2. Even after going in and manually changing a token's prototype, those settings will still sporadically reset to the aforementioned values.

**Comment by pwatson100** [comment]
Thank you. I will look into it.

**Comment by pwatson100** [comment]
Double checked and the Default Prototype Token Settings are working.  
If you have the Default Prototype Token Settings set - 
Character the default settings are:
      'prototypeToken.displayName': CONST.TOKEN_DISPLAY_MODES.OWNER_HOVER,
      'prototypeToken.displayBars': CONST.TOKEN_DISPLAY_MODES.OWNER_HOVER,
      'prototypeToken.disposition': CONST.TOKEN_DISPOSITIONS.FRIENDLY,
      'prototypeToken.bar1': { attribute: 'header.health' },
      'prototypeToken.vision': true,
      'prototypeToken.actorLink': true,
       tokenProto['prototypeToken.bar2'] = { attribute: 'header.stress' };

Creature settings are:
      'prototypeToken.displayName': CONST.TOKEN_DISPLAY_MODES.OWNER_HOVER,
      'prototypeToken.displayBars': CONST.TOKEN_DISPLAY_MODES.OWNER_HOVER,
      'tokenProto['prototypeToken.disposition'] = CONST.TOKEN_DISPOSITIONS.HOSTILE;
      'prototypeToken.bar1': { attribute: 'header.health' },
     'tokenProto['prototypeToken.vision'] = false;
     'tokenProto['prototypeToken.actorLink'] = false;

If the Default Prototype Token Settings is unchecked all actors default to:
      'prototypeToken.displayName': CONST.TOKEN_DISPLAY_MODES.OWNER_HOVER,
      'prototypeToken.displayBars': CONST.TOKEN_DISPLAY_MODES.OWNER_HOVER,
      'prototypeToken.disposition': CONST.TOKEN_DISPOSITIONS.FRIENDLY,
      'prototypeToken.bar1': { attribute: 'header.health' },
      'prototypeToken.vision': true,
      'prototypeToken.actorLink': true,
       tokenProto['prototypeToken.bar2'] = { attribute: 'header.stress' };

Overall the token settings are rudimentary and really only differentiate between characters and creatures.

What is not working is the settings for token vision.  With the V10 update I did not change the  'prototypeToken.vision', 'brightSight' and 'dimSight' parameters to the new Vision Enabled and Vision Range settings.
I have made the adjustments and it will be corrected in the next release.  

 I can't recreate your second issue.  I don't see anything obvious that could be causing it.  I will keep an eye on it. 

Regards,
 Paul.
