### ISSUE TITLE
Question or suggestion about Attribute only rolls

### ISSUE THREAD

**Issue by jacksands** [pwatson100/alienrpg#233]
As aways thanks for the amazing work!

I have a question/suggestion about the system.

I was asking to the community about the talent "Resilient"  pg 76, and if it would roll stress dice, and all agree that NO because all Attribute only roll do not rolls stress dice.

So I ask the rule about that, and they pointed me that on page 103

![image](https://user-images.githubusercontent.com/7229143/236632823-a55bc636-ffed-4efe-b5d9-d2b98b922425.png)

According to the community that meant that only Skills rolls add Stress Dices...

I don't know if that is true to all Attribute rolls, since it is not explicitly said, I imagine that you have some contact with the Writers and publisher to confirm that.

But if that is true could you add the automation for NO Stress dice on Attribute Only rolls, or add this option on the Settings of the System?

Once again, just as a suggestion and more a question that perhaps you can clarify with more properly!

Erich

**Comment by pwatson100** [comment]
I see your point but page 54 says:

ROLLS WITHOUT SKILL: If you don’t 
have the skill required for the particular action you want to perform, you can roll anyway—
simply roll a number of Base Dice equal to your attribute as well as any Stress Dice.

So overall I am not sure. 

But there are talents and opposed rolls where id does specifically state to roll against the attribute without stress dice.  

I will look into it and bit further.

**Comment by jacksands** [comment]
but in that case would not be an attribute + skill with skill value of zero instead of attribute only roll?

I know it looks the same but I don't know if that is by design...

anyway thanks for taking the time to answer!

**Comment by pwatson100** [comment]
Yea. It's not really clear so I'm going add to pop a dialogue box on attribute rolls with an option to not include the stress dice.

**Comment by jacksands** [comment]
> Yea. It's not really clear so I'm going add to pop a dialogue box on attribute rolls with an option to not include the stress dice.
> 
> The other question I have is can attribute rolls be pushed if stress dice are included???


Sorry to delay the response, running with work lately.

 I don't think it can push attribute rolls since if they do not roll stress and, even if rising normally the stress it would not allow for facehugger results...

perhaps since a pop up is asking if stress will be add to the roll, pushing should be attached to only be possible if stress are add, or also asked as option on the same pop up...

The art style of the book is amazing, but also made the space for writing small, to me that resulted in many cases of somewhat unclear rules becouse the writers needed to fit in the given space...

Still immensely fun to play!

As always, thanks for your time and effort!

**Comment by pwatson100** [comment]
No problem.    Family and work first!!  
Thank you again for your thoughts.  
I suspect you are right and attribute rolls+ stress can be pushed.  It's not a massive change for me to enable that. 
I have asked Free League if they could have a look at this issue when they have the time for an "official" ruling as I expect whatever I implement will raise some questions from the community.

**Comment by jacksands** [comment]
my pleasure to participate! 

... and it will be cool to have this insight from who writed it!   when you go deep  in the rules you start noticing the design thoughts of the writing, that make GMing ruling any situation effortless!!!

**Comment by pwatson100** [comment]
Martin ran the question past Tomas and this was the response.:
_Alright, got an answer from Tomas, and it's basically there's no hard distinction between skill and attribute rolls and the norm is that you roll with stress dice and can push. Some rolls are exceptions to this, like Resilient which is a "passive" roll for strength without stress dice._

So I in the system I will set it so if attribute rolls include stress dice they will be able to be pushed.

**Comment by pwatson100** [comment]
Fixed in the 3.1.0 update
