### ISSUE TITLE
Stress button issue in 0.7.8

### ISSUE THREAD

**Issue by GittaNaba** [pwatson100/alienrpg#25]
Hello,

I'm working on creating a virtual "Chariot of the Gods" oneshot using FoundryVTT.

First, many thanks for creating the game system !

I'm having an issue with stress button in 0.7.8 - when clicking on it, nothing happens. I've tried with all add-on modules deactivated,  same thing. It worked fin in 0.7.7 as far as I remember. Skills and attribute buttons work fine however.

Could you please look into it ?
Also, is there a place where I could suggest various improvements for this game system ?

Regards,

**Comment by pwatson100** [comment]
Hi,
   Many thanks.  There was an issue with the Stress button not working under Foundry V7.8.  I corrected the issue as soon as I spotted it on Friday.  Can you check you are using the latest version of AlienRPG.  It should be 1.2.19.    Some people have reported their modules systems are not seeing updates so you may need to force an update by putting the manifest link in the field at the bottom: 
https://github.com/pwatson100/alienrpg/releases/download/1.2.19/system.json

You are welcome to post suggestions here.  
Regards,
Paul.

**Comment by GittaNaba** [comment]
Hello,

I was indeed running 1.2.13 version, and for some reason update button didn't find anything. By using the link you provided, I was able to upgrade to version 1.2.19, and stress button behaviour is back to normal ! Thanks !

I'll be back with a list of suggestions.

**Comment by pwatson100** [comment]
Super.   
Look forward to seeing your suggestions.
