### ISSUE TITLE
Infinity icons

### ISSUE THREAD

**Issue by Leroy0790** [pwatson100/alienrpg#252]
When a character carries more weight than allowed, the overweight icon starts to appear infinitely over the token crashing the game.

**Comment by pwatson100** [comment]
I am unable to recreate the issue you are seeing.  Could you try disabling all (non Alien) modules and see if it still happens.

**Comment by Melkkart** [comment]
Hi, with 0 modules installed. 
![image](https://github.com/pwatson100/alienrpg/assets/123239719/958408d4-bd3a-4fff-b56b-6ba2c6502fd9)
drop item ...
![image](https://github.com/pwatson100/alienrpg/assets/123239719/e3767cbd-6fbf-4ebb-891b-738a8625714f)
I select sheet Actor ...
![image](https://github.com/pwatson100/alienrpg/assets/123239719/4abb5e7f-58af-4a24-a01a-f528385afa5c)


I had a hard time reproducing the bug. 
The strange thing is that I could only get it in the Spanish version, but I don't think that has anything to do with it.

**Comment by pwatson100** [comment]
Thank you. That gives me a lead. I am Bly test in English so it seems something odd might be going on with other languages enabled.

**Comment by pwatson100** [comment]
Yep.  As soon as you mentioned other languages, I had an idea what was going wrong in V11 and I was right.  
When it checks to see if the condition exists it's trying to compare 'encumbered' against the localised version of encumbered ('gravado' in spanish), so it fails.
Now to work out how to fix it.

**Comment by Melkkart** [comment]
I am grateful to you.

**Comment by pwatson100** [comment]
I have released version 3.1.4 which should correct the issue.
