### ISSUE TITLE
Chat Text colors are nearly impossible to read

### ISSUE THREAD

**Issue by BBendriss** [pwatson100/alienrpg#257]
I don't know if it's just me, but the CHAT TEXT for all of the Alien RPG products are impossible to read. I literally have to highlight them with a mouse each time to read what players are saying. Is there a setting I'm missing or is this the baffling intention?  I see we can change Journal and Character sheet fonts and text, but nothing for the chat.   example:

https://gyazo.com/4ef8216e58471dd3b2d2cbbbd1ccc7c9

**Comment by pwatson100** [comment]
The chat colour as fixed by the system and can't be changed by the user/GM.  
What version of Alien are you running? 
This could be a module interfering; can you disable all the non-alien modules and test please.

**Comment by BBendriss** [comment]
Hello,

Thank you for the reply! I'm running:

Foundry v11
Alien RPG v 3.1.6

The chat text that I showed the screenshot of is when you do an /emote
command. you get this dim grey on black text which is impossible to read.
Is that how it should look?  I will try what you say and disable all
modules and see.

**Comment by BBendriss** [comment]
You are correct. I disabled all the modules and slowly added them back
until I found the problem. When enabling this one "Cautious Gamemaster's
Pack", it creates that greyed out text.

https://github.com/cs96and/FoundryVTT-CGMP

Thanks for the advice!

**Comment by pwatson100** [comment]
Glad you found the issue.
