### ISSUE TITLE
BBW Macro "Build a Better World" broken

### ISSUE THREAD

**Issue by 9littlebees** [pwatson100/alienrpg#259]
The macro doesn't do anything when clicked. Here's the output from the console.

![BBW-Macro-Error](https://github.com/pwatson100/alienrpg/assets/10364404/a0d26c1b-68df-47f9-af7e-ff9d7d7ecdd9)

Using Foundry v11.315 and Alien module 3.1.7

**Comment by pwatson100** [comment]
Hi Matt,
   An F5 or restarting the world after the module install fixes the problem.  
The issue is that the module adds a new system class (BBWSystemCreator) which requires a restart once it's been created.  It's not something I beleive I can do from within the module.

**Comment by 9littlebees** [comment]
Ah, I didn't try that. I'll give it a go when I'm not at work and update here.

**Comment by 9littlebees** [comment]
Refreshing did the trick - thanks, Paul!
