### ISSUE TITLE
Suggestion: Possibility to hide initiative card ONLY of NPC/Enemies?

### ISSUE THREAD

**Issue by jacksands** [pwatson100/alienrpg#261]
It would be possible to hide de initiative card on chat only of NPC/Enemies?

Now it is possible to hide ALL or none in the settings, but it would be awesome to be able to hide only enemies and npcs...

Even hidden enemies on the combat tracker stills shows the card...

In any case tks for the amazing module!

![image](https://github.com/pwatson100/alienrpg/assets/7229143/d291cde7-098a-4e79-817e-133ae76c144f)
![Screenshot_2](https://github.com/pwatson100/alienrpg/assets/7229143/13bd72fe-c865-4a5f-b864-a31fe13e86b0)

**Comment by pwatson100** [comment]
Sory for the delay in responding.  
This is a great suggestion.  
Took a little while but I can get it so if the Actor (token) is hidden when added to the tracker (so appears hidden there as well), when the initiative is rolled there is no chat message displayed for the players or GM.

**Comment by pwatson100** [comment]
Corrcted in the latest release 3.1.8.
