### ISSUE TITLE
Power Supply Button Missing..?

### ISSUE THREAD

**Issue by BBendriss** [pwatson100/alienrpg#262]
Recently needed to make a supply check for power.. and realized there is no button. Is that intended or is something glitched?
https://gyazo.com/fe0a6bcae3c902f489fb9548bf79b2a9

Foundry v11 Build 315  ; Alien RPG v 3.1.7

**Comment by pwatson100** [comment]
Power supply rolls are made against the item on the items tab:
![image](https://github.com/pwatson100/alienrpg/assets/19948257/7db05c88-6d2b-4953-bd57-655c084e17e2)

**Comment by BBendriss** [comment]
Thank you - that was driving me mad :)
