### ISSUE TITLE
Firefox hanging on SVG load

### ISSUE THREAD

**Issue by audioeng89** [pwatson100/alienrpg#263]
Firefox fails to load Views or update tokens when a token with certain conditions (such as radiation) is present. While the UI loads, the map remains black. You also recieve the error `You cannot switch Scenes until resources finish loading for your current View` while attempting to navigate to another view.

I see the following error in the Firefox console:

`Uncaught Error: The SVG image must have width and height defined (in pixels), canvas API needs them.
    onload index.js:126
[index.js:126](https://*****.com/node_modules/eventemitter3/index.js)
    onload index.js:126`

After digging into the module files, I found that conditions that load an SVG file for the token condition image (overwatch, feezing, radiation, etc) cause the bug. Views work fine for tokens with conditions that load a .webp icon, such as weight or injury.

Foundry Virtual Tabletop Versoin 11 Stable - Build 315
Alien RPG 3.1.7
Firefox 124.0 (64-bit)
Tested on a fresh world with no modules enabled

**Comment by pwatson100** [comment]
Moved away from using svg images so this should be resolved in the next release.

**Comment by pwatson100** [comment]
Corrcted in the latest release 3.1.8.
