### ISSUE TITLE
Translation error

### ISSUE THREAD

**Issue by FederSchakal** [pwatson100/alienrpg#264]
Hey,
the German version of the class “Machinist” is misspelled. It is currently translated as "Machinist" but means "Maschinist".

Wish a great day!

**Comment by pwatson100** [comment]
Thank you for this.  Would "Raufbold" be the correct translation for "Roughneck"?

**Comment by Raldanash** [comment]
It depends. Raufbold is someone who is rough and likes to brawl. It has many similar connotations but is not 100% the same. Can't think of anything better right now, though. Grobian?... Rowdy?

**Comment by pwatson100** [comment]
Thinking about the (non offensive) meaning of roughneck: 
"Person who's job is hard manual labour"

Would there be something more appropriate in German ?

**Comment by Raldanash** [comment]
"Malocher"  comes to my mind. Malochen is a slang word for hard, manual work. like a "grafter"

**Comment by pwatson100** [comment]
Will be changed to "Maschinist" in the next release.

**Comment by pwatson100** [comment]
Corrcted in the latest release 3.1.8.
