### ISSUE TITLE
pack.private error message

### ISSUE THREAD

**Issue by spookymonster** [pwatson100/alienrpg#265]
Console log shows the following errors on Foundry VTT startup. Server, game system, and related modules are all up to date. Any suggestions?

![image](https://github.com/pwatson100/alienrpg/assets/16195156/60c18297-413c-4fae-8b5f-86147cf5388d)

![image](https://github.com/pwatson100/alienrpg/assets/16195156/dd57f10c-0173-44a1-b274-c3464e4c7c14)

![image](https://github.com/pwatson100/alienrpg/assets/16195156/a0e46c64-c2f3-4366-8a1e-8e9786422f19)

**Comment by pwatson100** [comment]
Hi,  You can ignore those errors.  pack.private has been left in to maintain compatibility with FVTT V10.  It will disappear in future releases.
