### ISSUE TITLE
Question:  How I do to import only part of an adventure compendium?

### ISSUE THREAD

**Issue by jacksands** [pwatson100/alienrpg#284]
First! Good day and tks for all your work and help!

To my knowledge you made or help made the modules for BBW and the other adventures for alien, that is why I'm asking here...

My question is, how I make a partial import from the module? in this case I have an active world, but I made a mistake and lost some assets, I wish to reimport it, but it seems that the module allow only for a full reimport, that would overwrite some of my work.

I know I can import on a different world and export from there, but that seems a bit over complicated....

can a partial import be done, like searching for specific scene or item and drag only that to the world?

![bbw](https://github.com/user-attachments/assets/d5cf6e2a-7a43-4ac7-85b6-982389a87da2)

Aside from that I was able to add my custom panic to the new system and noted that maybe a custom way to roll from a table is in the code...   it is on the way?   

As always, tks!!

**Comment by pwatson100** [comment]
Hi,  I did all the Alien modules :)
Therer are two ways:
Go To -Configure Settings > The module you want to import from.
You should see two options, "Re-Import" and "Import Assets".
 "Re-Import" will reimport any assets that have been deleted but will not touch any existing assets. 
 "Import Assets" will open a window which will allow you to select specific assets to import.  This will only work in the asset exists in the world and it will overwtite it.  So this is usefull if you want to reset the actors to rerun a scenario.

**Comment by jacksands** [comment]
TKS!!!

I'm so used to using compendium for imports that I didn't look in the settings!

sorry and tks!
