### ISSUE TITLE
Panicked Condition is not being turned on when a Panic roll is made

### ISSUE THREAD

**Issue by jmp120** [pwatson100/alienrpg#289]
Panic Level is not visible unless the Panicked Condition is on. It would make sense for this Condition to be turned on automatically when the first Panic roll is made. I'm not sure if it did in the past but it does not in release 3.2.1.

**Comment by pwatson100** [comment]
I will double check but when the p
Panic is cleared the panic level is reset to zero. So unless the actor has an active Panic condition it's meaningless.  Panic level is something I had to introduce to be able to calculate the "more panic" rule.

**Comment by jmp120** [comment]
I understand the intent. My point is that if a greater than zero value is ever in the Panic Level, the Panic Condition should be turned on so you can see that there is a value there. Completely understand the clearing the Panic level but it's not obvious you have a Panic Level unless the Panicked Condition is turned on. Hope that helps, thanks!

**Comment by pwatson100** [comment]
I have checked the code and it is operating as intended.  
An actor only has a panic level when they have the Panicked condition (stress rolls of 7 or greater).
