### ISSUE TITLE
[Request] Add modifier prompt to rolls

### ISSUE THREAD

**Issue by mkahvi** [pwatson100/alienrpg#291]
It's incredibly difficult to have modifications to pools that the rules state, like distance modifier to stealth, or the modifier from taking aim action, or the bonus from Command, and also for any stunts or other actions that give bonuses to followup rolls.

So it would be nice if clicking skill or weapon would give a prompt that allowed to enter such modifiers that affect only that one roll.

**Comment by pwatson100** [comment]
Right clicking on skills or items does pop a box allowing you to add or remove base and stress dice.
But I do like the idea of having modifier options for the weapons so will look into it.

**Comment by mkahvi** [comment]
I didn't know about the right clicking. Seems to work fine. And it seems it works for weapons too already, so I'll close this issue as irrelevant.
