### ISSUE TITLE
Remove Item from Character Sheet?

### ISSUE THREAD

**Issue by JimmiWazEre** [pwatson100/alienrpg#30]
Hi,

I can pass an actor an item, then toggle it between active and inactive. But I can't see how to remove an item from the character sheet?

**Comment by pwatson100** [comment]
Left click on the right hand icon and you will open the context sensitive menu.  You should see Edit and Delete there.

**Comment by JimmiWazEre** [comment]
Thanks, You have to right click the icon (at least you do in my setup) - I had been left clicking that icon and wondering why it did nothing :D

**Comment by pwatson100** [comment]
Super.  There is a setting that switches the mouse buttons so I confused myself :).
