### ISSUE TITLE
Free Text box on Inventory tab of character sheet

### ISSUE THREAD

**Issue by JimmiWazEre** [pwatson100/alienrpg#33]
Hi Paul,

Great piece of kit you've made! One thing that is a bit clunky is inventory management - if I make up a random nicknack on the fly that my PCs have found, I've got to currntly go through the process of making it an item before they can add it to their inventory.

This is not particulary conducive to a free flowing game, so it woul dbe quite nice if the inventory tab of the character sheet had a free text box for writing down small items that don't neccecarily carry any game rules - stuff like keys or a pack of cigarettes etc

**Comment by pwatson100** [comment]
Thank you.  I am glad it's working for you.  
I should be able t add a small text box at the bottom of the inventory sheet for jotting down ad-hoc items.  Though these would not have nay actual game effect (mods etc.).
Would that do the trick?

**Comment by JimmiWazEre** [comment]
It would, that would be perfect

**Comment by pwatson100** [comment]
The only problem I am having is if there are a lot of items in the list it gets pushed down and can require the user to scroll down.

**Comment by JimmiWazEre** [comment]
I'd say it's not often you'll have loads of items to be honest, and
personally I'd rather it was there even if I had to scroll down for it.

Up to you mate 🙂

**Comment by pwatson100** [comment]
:)   I want to see if I can tidy it up a bit but it will be in the next release (probably next week).

**Comment by pwatson100** [comment]
I have done the tidy up so it will be in the next release.

**Comment by JimmiWazEre** [comment]
Nice one, thanks
