### ISSUE TITLE
How to make talents dynamic?

### ISSUE THREAD

**Issue by 9littlebees** [pwatson100/alienrpg#38]
There are quite a few talents which modify some of the core mechanic which are not possible to be used with the system as is. They are:

(1) There are several talents which alter which attribute a skill is connected to (Take Control on p75, Flyweight and Menacing on p78, and Stoic on p79), but there is no way to modify which attribute the skills are connected to (other than using a modifier each time that skill is used).

(2) There are several talents which allow pushing more than once, gaining a stress each time, but the dice roller only lets you push once per roll.

(3) The general talent _Pack Mule_ allows you to carry twice as many objects as normal before becoming encumbered (page 79), but it does not seem to be possible to alter the Encumbrance value, which is auto-calculated.

Are there any solutions or workarounds to allow some of these to be implemented, especially (1) or (2) (without too much in the way of coding)? We're planning on using this Alien system on Foundry for a streamed game ([this YT channel](https://www.youtube.com/threeskullstavern)), but already we are seeing some issues with the talents for two of the PCs.

**Comment by pwatson100** [comment]
Hi Matt,
   Talents are a particular thorn in my side. Since I implemented the modifiers for items I have been thinking how I might do it.  There are a couple of issues.  
As they all work differently their effects would have to be hardcoded. Not a massive problem but I can't include the talents in the core system (they will be available in the paid modules) as that would break my agreement with Free League. 
Once the modules are released it is something I want to have another look at.

**Comment by MickeyP2K** [comment]
I have been thinking about the pushing twice mechanic as I need to implement it in my Babylon 5 module.

I'd love to discuss hypothetical ways to do this @pwatson100

**Comment by 9littlebees** [comment]
OK, I understand. I think talent type (1) is pretty easy to workaround (just using modifiers each time that skill is used). And I think we can avoid Pack Mule for the campaign. But talent type 2 is a bit of a problematic one. Is there no way to add a flag to the character sheet which would allow that character to push multiple times? Could be a menu with a list of attributes which the character ticks. That way the functionality is there, but no text from the books?

**Comment by 9littlebees** [comment]
As an example, you could put a simple toggle in here with a menu that lets you select which attribute can be pushed multiple times. Maybe only the GM can enable it, to prevent it from being abused?

![image](https://user-images.githubusercontent.com/10364404/108571944-8355ab00-7311-11eb-92ee-807efd7effc8.png)

**Comment by MickeyP2K** [comment]
As an MVP I'd say allow users to mark the double push simply because if you can't trust players not to abuse, you're playing with the wrong group :)

**Comment by pwatson100** [comment]
I wonder how the Roll20 and Fantasy Grounds systems handle this????

**Comment by MickeyP2K** [comment]
The only with rolling again is you're only meant to roll the 'misses' aren't you? Can you modify before the roll perhaps?

**Comment by pwatson100** [comment]
Yea.  Right click to get the modifier box.  
Just to complicate things more, the multiple push rolls for a few of the talents only allow pushes for skills based on specific attributes:
Cunning - You can push any skill roll based on Wits twice, not just once like other characters.
Compassion - You can push any skill roll based on Empathy twice, not just once like other characters.

AGGHH Talents!!!

**Comment by pwatson100** [comment]
So on the bright side I have "Pack Mule" working.  If the PC has the Talent their encumbrance increases from 50% to 75%. 

With the multiple combinations of "extra push for attribute X skills" I am going to have to work on a generic multi push option as trying to code for all eventualities would be a mess.

**Comment by 9littlebees** [comment]
> So on the bright side I have "Pack Mule" working. If the PC has the Talent their encumbrance increases from 50% to 75%.
> 
> With the multiple combinations of "extra push for attribute X skills" I am going to have to work on a generic multi push option as trying to code for all eventualities would be a mess.

I saw there was an update and applied it, thinking this had been implemented somehow, but I can't get it to apply. I have a General Talent called "Pack Mule" and when I add it to a PC, nothing happens to their Encumbrance value...

**Comment by pwatson100** [comment]
It's not released yet but will be in the next one.  I needed to get the latest version out before the official packs release then realised I could get pack mules working quite easily so the timing was a bit off.    
I am still thinking about how I can do some of the other Talents. I think I might have a solution for the ones that modify attribute based skills.  
Looking through them I will not be able to do all of them as some have party/range effects lowering stress as well as the "once during a round/session" type effects.  
If all goes to plan I should have the a new release out next week.

**Comment by pwatson100** [comment]
So a bit of a compromise. Pack Mule will have an in game effect.  The rest of the Talents I am afraid are too complex (at present) to fully automate.  But.. in the next release players will have the option to push a roll twice. 

I hope this goes part of the way to meeting your requirements Matt.

**Comment by 9littlebees** [comment]
> So a bit of a compromise. Pack Mule will have an in game effect. The rest of the Talents I am afraid are too complex (at present) to fully automate. But.. in the next release players will have the option to push a roll twice.
> 
> I hope this goes part of the way to meeting your requirements Matt.

I suppose this applies to the official module, as well, since the functionality is built into the core system? Or does buying the official module solve this problem, when applying a relevant talent?

**Comment by pwatson100** [comment]
Multi push is in the latest published version (1.3.0) along with Pack Mule talent adjustment.  I think that is about as far I I can do with Talents without a major rewrite.   If possible I will try to include more.  
I am going to close this ticket for now.
