### ISSUE TITLE
Make custom rolls show results in chat history

### ISSUE THREAD

**Issue by MickeyP2K** [pwatson100/alienrpg#40]
I tried the custom dice roll notation but it doesn't display the results in the history, just the number of dice rolled (from memory I need to double check later).

It would be great if it showed the individual dice results like the 'proper' skill rolls.

**Comment by pwatson100** [comment]
The dice rolling macros are the easiest way to do it.  But I just did this:
![image](https://user-images.githubusercontent.com/19948257/108598360-2eec1300-7385-11eb-9e90-1ab4d9f746ff.png)

**Comment by MickeyP2K** [comment]
Doh! Sorry I was doing that but I didn't realise you could click on it to expand the dice roll! Brilliant thanks!

**Comment by MickeyP2K** [comment]
Sorry one last comment...  You need to add some styles to remove the default sepia filter behaviour:

.dice-tooltip .dice-rolls .roll {
  filter: none;
}

.dice-tooltip .dice-rolls .roll.max {
  filter: none;
}

.dice-tooltip .dice-rolls .roll.min {
  filter: none;
}

**Comment by pwatson100** [comment]
Thanks,  That's done.
