### ISSUE TITLE
Fonts not showing correctly

### ISSUE THREAD

**Issue by jpwhale** [pwatson100/alienrpg#48]
The fonts defined in the CSS aren't being used.

![Screenshot_2021-02-26_20-45-41](https://user-images.githubusercontent.com/60820258/109347986-3c693780-7874-11eb-9268-41ca3d35ffdf.png)

I'm using Chromium 88.0.4324.182 on Manjaro Linux.

I'm no expert in these matters, but I did find this:

![Screenshot_2021-02-26_20-52-48](https://user-images.githubusercontent.com/60820258/109348381-bd283380-7874-11eb-829d-57d405600b32.png)

Forgive the big arrow. That's probably not git savvy at all :)

Let me know if and how I can supply more info if needed.

**Comment by pwatson100** [comment]
Thank you for letting me know.  I will take a look.  I don't load/supply all the fonts and rely on them being installed by the OS (they are in Windows) so it may possible the font is not present on your system.   
The information you sent is really helpful.

I will keep you posted on the progress.

**Comment by jpwhale** [comment]
I installed the fonts locally, but that doesn't change anything. `--alienfont: undefined` still shows up.

**Comment by pwatson100** [comment]
Thank you again.   I will see if I can find out what is going on.

**Comment by jpwhale** [comment]
Works perfectly now!

**Comment by pwatson100** [comment]
Ah.  That's good.  I made a slight change but did not think that would actually fix the issue.  Glad it did :).
