### ISSUE TITLE
Add a new condition : "Burning" to PC, NPC and Creatures

### ISSUE THREAD

**Issue by pwatson100** [pwatson100/alienrpg#61]
Add a new condition : "Burning" to PC, NPC and Creatures, with an automated system to roll damage as long as the victim is burning following the rules.

Might be able to do this with Active Effects?

**Comment by GittaNaba2021** [comment]
If I may add a suggestion : make it red and blinking within the Character sheet, just like "Panicked", so players and GM do not forget it.

**Comment by pwatson100** [comment]
It's not an official condition within the rules.  But I may add it as an active effect as you suggest.
