### ISSUE TITLE
Importing Stunt from the compendium and dragging it to the sheet makes the Skill Roll Broken

### ISSUE THREAD

**Issue by superseva** [pwatson100/alienrpg#7]
![Alien Screenshot 2020-10-03 211518](https://user-images.githubusercontent.com/4093045/95000060-ceb72900-05bd-11eb-90a7-3eac47353660.png)

**Comment by superseva** [comment]
Bah, never mind. I was stupid not reading update notes. The items were already imported to the game.
Sorry

**Comment by pwatson100** [comment]
Ok no problem. I wanted to make adding stunts as easy as possible so imported the skills from a he compendium as mart of the update. If I had not done that it would have broken the character sheet.  
Glad you making no use of them 😀
