### ISSUE TITLE
Spanish translation error: Wits

### ISSUE THREAD

**Issue by Eldebor** [pwatson100/alienrpg#70]
It is a very minor error but "Wits" is translated as "Voluntad". It is more correct to translate it as "Ingenio" or "Inteligencia".
Spanish word "Voluntad" is "Will" in english.

**Comment by pwatson100** [comment]
Thank you I have changed it to "Ingenio" as it does not look odd on the sheet.   I hope that is OK?

**Comment by pwatson100** [comment]
Fixed in version 1.3.5
