### ISSUE TITLE
Stress and health misplaced in compendium.

### ISSUE THREAD

**Issue by MichalKolesinski** [pwatson100/alienrpg#74]
![screenshot1](https://user-images.githubusercontent.com/39199872/115973364-c708a300-a554-11eb-9434-c1d1339f5e5f.png)

one more thing is information about blocking, which states: if they're left with no <spanclass, basesymbol...> 
![Screenshot2](https://user-images.githubusercontent.com/39199872/115973417-0a631180-a555-11eb-8b72-31409cc9faff.png)

**Comment by pwatson100** [comment]
Thank you for this.  With the first one I have the headings the wrong way round. The second one is me editor putting in line breaks that muck up some of the embedded image links.  
I will add them to the next update.
