### ISSUE TITLE
Add a new condition : "Acid burn" for PC and NPC

### ISSUE THREAD

**Issue by GittaNaba2021** [pwatson100/alienrpg#79]
Hello,

It would be useful to add a "Acid burn" condition, similar to "Burning" condition:

- Add a item for it within the "Conditions" box within Character sheet, making it red and blinking when activated, just like "Panicked".
- If possible, allow GM or player to click on it to roll for Acid damage, and removing the condition if damage is 0, or reducing dices rolled by half, as per rules. Which means it is required to ask GM/player what the initial acid damage amounts to.

Thanks for listening !

**Comment by pwatson100** [comment]
It's not an official condition within the rules.  But I may add it as an active effect as you suggest.
