### ISSUE TITLE
Big Shoutout and Thanks to all your hard work!

### ISSUE THREAD

**Issue by Sonny-Crockett** [pwatson100/alienrpg#8]
My partner and I love Alien and we played with your system for several sessions for one of the modules. We just wanted to thank you for the recent updates to v7.5, and the dice rolling, and all the other little tweaks and UI improvements. 

It's been really great and just wanted to say thank you again!

**Comment by pwatson100** [comment]
Thank you for your kind feedback.   It's really good to know that the system is being used and that you are enjoying it.  
Please feel free to let me know if there is anything I could improve on from a GM or Player perspective.   
I have been working on getting the system working with Token Action HUD.   I use it for PF2E and am a big fan. Hopefully it will help speed up combat as you won't need to keep opening the character sheets.    I have it working for PC's and Synths just need to get Creatures setup.  Then I can (hopefully) get it released by the author.  

Thanks again.  Try not to kill too many PC's :) .
