### ISSUE TITLE
Add panic roll button for PCs

### ISSUE THREAD

**Issue by jbhaywood** [pwatson100/alienrpg#82]
If I roll on the panic table, it always results in a value between 1-6 and reports in chat that the character is fine. Even if they just roll a d6, I need to mentally add their stress and then try to read the text within the table itself, which is hard to read because the text includes html markup and runs out of the box. Or I can ignore the roll table completely and use a separate sheet outside of Foundry. But if players could roll for their own panic from their sheet, it could automatically include stress and they'd get an accurate result in chat with an easy to read description.

**Comment by pwatson100** [comment]
Have you read the MO/TH/ER Instructions?  They document the button to press for stress rolls.
