### ISSUE TITLE
Can't remove items from character inventories

### ISSUE THREAD

**Issue by symulation** [pwatson100/alienrpg#95]
A L I E N  is my first exposure to Foundry VTT and it is brilliant.  Thank you.  The walkthroughs on YouTube were also really helpful.

Given this is my first exposure to Foundry I might be missing something but after a bit of searching it seems not.

The problem I'm having is that once an item is added to a character sheet I can't seem to get it off (other than editing a .db file directly and sometimes that doesn't go so well).  From looking around in various chats it seems that there should be a "remove" button beside the items but this isn't there.  Only an icon for editing the item.  I can move  items to be inactive but this isn't the same thing.  I'm running on MacOS if that matters.

Is something missing or am I missing something?

**Comment by pwatson100** [comment]
As documented in the MU/TH/ER Instruction journal entry, right clicking on the leftmost icon on the inventory tab will pop up a context menu with a delete option. 
![image](https://user-images.githubusercontent.com/19948257/119898049-30574980-bf39-11eb-95e7-e85cc172742a.png)

There is also a copy of the user guide here: https://github.com/pwatson100/alienrpg/wiki/MU-TH-ER-Instructions

**Comment by symulation** [comment]
Got it.  Right there at the top, as you said.

Thank you.
