### ISSUE TITLE
Can't "Return to Setup" from the "Join Game Session" screen

### ISSUE THREAD

**Issue by symulation** [pwatson100/alienrpg#96]
Hitting "Return to Setup" here results in an "invalid access key" warning even though no access key has been set.

Joining the game session as the GM (with no access key) and choosing "Return to Setup" from the settings menu results in a return to the setup screen, as expected.

**Comment by pwatson100** [comment]
Hi,  This is a Foundry issue so should be raised with the team on the Foundry discord.

**Comment by symulation** [comment]
Thanks.  Will do.
